# Basic Hill Climbing Algorithm

Solves the Symmetric TSP using a basic Hill Climbing algorithm

In [1]:
# import Pkg
#Pkg.add("DataFrames")
#Pkg.add("CSV")
#Pkg.add("Distances")

In [29]:
using DataFrames
using CSV
using Distances
using LinearAlgebra
using Random

In [36]:
st70 = CSV.read("data/st70.csv");

In [37]:
head(st70, 10)

10×3 DataFrame
│ Row │ city  │ x     │ y     │
│     │ Int64 │ Int64 │ Int64 │
├─────┼───────┼───────┼───────┤
│ 1   │ 1     │ 64    │ 96    │
│ 2   │ 2     │ 80    │ 39    │
│ 3   │ 3     │ 69    │ 23    │
│ 4   │ 4     │ 72    │ 42    │
│ 5   │ 5     │ 48    │ 67    │
│ 6   │ 6     │ 58    │ 43    │
│ 7   │ 7     │ 81    │ 34    │
│ 8   │ 8     │ 79    │ 17    │
│ 9   │ 9     │ 30    │ 23    │
│ 10  │ 10    │ 42    │ 67    │

In [38]:
euclidean(city1, city2) = norm(city1 - city2)

euclidean (generic function with 1 method)

In [37]:
"""
    euclidean_distance_matrix(cities)

Compute a matrix of euclidean distances between
city x, y coordinate pairs

# Examples
```julia-repl 
julia> using Random;

julia> coords = rand(1:50, 5, 2)
5×2 Array{Int64,2}:
 16  42
 10  15
 44  36
 32  42
 28  39

julia> euclidean_distance_matrix(coords)
5×5 Array{Float64,2}:
  0.0     27.6586  28.6356  16.0     12.3693
 27.6586   0.0     39.9625  34.8281  30.0
 28.6356  39.9625   0.0     13.4164  16.2788
 16.0     34.8281  13.4164   0.0      5.0
 12.3693  30.0     16.2788   5.0      0.0
```
"""
function euclidean_distance_matrix(cities)
    nrows = size(cities)[1]
    matrix = zeros(nrows, nrows)
    
    row = 1
    
    for city1 in 1:nrows
        col = 1
        for city2 in 1:nrows
            matrix[row, col] = norm(cities[city1, 1:2]-cities[city2, 1:2])
            col+=1
        end
        row +=1
    end
        
    return matrix
end

euclidean_distance_matrix

In [11]:
trim_cities(df, ncities) = Array(df[2:end])[1:ncities, :]

trim_cities (generic function with 1 method)

In [14]:
small = trim_cities(st70, 8);

In [38]:
matrix = euclidean_distance_matrix(small)

8×8 Array{Float64,2}:
  0.0     59.203    73.171   54.5894  33.121   53.3385  64.2884   80.4114
 59.203    0.0      19.4165   8.544   42.5206  22.3607   5.09902  22.0227
 73.171   19.4165    0.0     19.2354  48.7545  22.8254  16.2788   11.6619
 54.5894   8.544    19.2354   0.0     34.6554  14.0357  12.0416   25.9615
 33.121   42.5206   48.7545  34.6554   0.0     26.0     46.669    58.8303
 53.3385  22.3607   22.8254  14.0357  26.0      0.0     24.6982   33.4215
 64.2884   5.09902  16.2788  12.0416  46.669   24.6982   0.0      17.1172
 80.4114  22.0227   11.6619  25.9615  58.8303  33.4215  17.1172    0.0